### ISSUE TITLE
Generated a empty docset

### ISSUE THREAD

**Issue by SilkSong** [Kapeli/javadocset#14]
I am using this tool to generate the Java SE 17 docset. I received this warning on my iTerm:  `Warning: could not determine type for . Please tell the developer about this`. It showed that "added 0 entries" and the final Java SE 16 docset proved to be empty. Hope it can be solved.

If there is another way to generate a Java 17 docset, just let me know.

**Comment by Kapeli** [comment]
Java SE17 is available within Dash (in Preferences > Downloads). Any reason you're not using that docset?

**Comment by SilkSong** [comment]
I don't know why. Here is the screenshot of my Dash. The latest version Java doc I can install is Java 12.
<img width="820" alt="Screen Shot 2021-11-02 at 15 02 40" src="https://user-images.githubusercontent.com/12102526/139873600-f8ccd0ce-7fc9-4f03-b631-f07bea67bb26.png">

**Comment by Kapeli** [comment]
Please update Dash to the latest version (6.1.0).
