### ISSUE TITLE
Namespace methods with their class name

### ISSUE THREAD

**Issue by FichteFoll** [Kapeli/javadocset#15]
Some methods in Java are overloaded a lot, such as `List` or `Set` methods, or they just occure quite frequently due to name collisions. However, in the docset the entry names only include the method name and not the class, which makes navigating to the one that you need quite a task, whereas the Python docset includes the module (and class) name and makes navigation a lot easier.

![2021-11-05_12-50-18_zeal_java-addAll](https://user-images.githubusercontent.com/931051/140506477-05387e58-11e9-4230-8622-0e9c63a8938d.png)

![2021-11-05_12-51-20_zeal_python-update](https://user-images.githubusercontent.com/931051/140506513-994c4ea3-ab70-4d3a-b663-4750dd42b358.png)

**Comment by FichteFoll** [comment]
Is this something you would be interested in in general? I run into this problem quite frequently when I work with Java and I always get annoyed by it. However, I don't have a Mac and don't know Objective-C, so it's not exactly something I can implement myself.

What I'm imagining is for to be prefixed by the package namespace and then separated from the function name by a hash sign, because that's how [JavaDoc references class members in {@link}](https://docs.oracle.com/javase/7/docs/technotes/tools/windows/javadoc.html#link) and others. For a method like `addAll` in the above screenshot, that would then become (signatues omitted):
- [`javax.naming.Name#addAll`](https://docs.oracle.com/en/java/javase/21/docs/api/java.naming/javax/naming/Name.html#addAll(int,javax.naming.Name)) (has 2 overloads)
- [`javax.management.relation.RoleList#addAll`](https://docs.oracle.com/en/java/javase/21/docs/api/java.management/javax/management/relation/RoleList.html#addAll(int,javax.management.relation.RoleList)) (has 2 overloads)
- [`javax.management.AttributeList#addAll`](https://docs.oracle.com/en/java/javase/21/docs/api/java.management/javax/management/AttributeList.html#addAll(int,java.util.Collection)) (has 4 overloads
- etc

This information is at least available on each packge and constructed from the package name and the class name.

**Comment by FichteFoll** [comment]
I also wanted to report the same issue for the Haskell docset, but didn't find a repo for it. Could you point me to where I can create that?

**Comment by Kapeli** [comment]
This isn't something that affects Dash so it's unlikely it'll ever be changed. Sorry. This is how it looks in Dash:

![Screenshot 2023-12-11 at 10 43 32](https://github.com/Kapeli/javadocset/assets/1445635/af4af7ad-936a-4653-b897-3b0a8286b656)

**Comment by FichteFoll** [comment]
Can you also query for `LdapName#addAll` or (`LdapName.addAll`) in Dash to narrow down the results? Does the Haskell docset have the same metadata?

**Comment by Kapeli** [comment]
Not currently, but "LdapName addAll" works. Screenshot for Haskell:

![Screenshot 2023-12-11 at 13 28 42](https://github.com/Kapeli/javadocset/assets/1445635/404c93f3-f2cf-4285-ac45-1c7945d94f8b)

**Comment by FichteFoll** [comment]
Thanks. I'll see about adding this to Zeal. Sounds simpler than modifying multiple docsets anyway, if this information is already there somewhere.

**Comment by FichteFoll** [comment]
Closing since I created an issue for Zeal now. Unfortunately I don't have time to get into an unfamiliar code base written in a largely unfamiliar language at the moment. Thanks again for your speedy replies.
