### ISSUE TITLE
Generating empty docset

### ISSUE THREAD

**Issue by admlvntv** [Kapeli/javadocset#16]
Hello, I'm trying to [update WPILib in the user contributed repo](https://github.com/Kapeli/Dash-User-Contributions/pull/4658), and I've been stuck with receiving an empty docset. I've only gotten the error `Warning: could not determine type for . Please tell the developer about this!` over and over again. Attached is a screenshot of the empty docSet.dsidx next to the index-all.html file. Any way to fix this?

![](https://user-images.githubusercontent.com/64713401/277168460-ac0cac9f-4aab-466b-9e80-c9b510335073.png)

**Comment by Kapeli** [comment]
I think I fixed it. Please redownload javadocset and try again.

**Comment by admlvntv** [comment]
That worked, thanks!
