### ISSUE TITLE
Mention containing class/iface for methods, fields, and nested classes

### ISSUE THREAD

**Issue by tsdh** [Kapeli/javadocset#4]
I assume the Java SDK docset (and possibly other docsets) that are available in Dash are generated with this tool.  The problem I have with it is that it indexes methods just by their simple name.  For example, when you search for `getName` you'll get a list of one hundred or more matches and have no easy way to figure out which method in the list belongs to which class or interface.  The same applies to fields and also to nested classes.

I'd suggest to index methods and fields using a scheme like `methodOrFieldName (ContainingClassOrIFace)` or similar where the container is already visible in the search results.

**Comment by Kapeli** [comment]
Dash shows the FQN of the class a method belongs to when you press Enter while the result is highlighted or when you click the badge that is shown next to the result or the java icon that is shown on the left of the result.

![screen shot 2015-03-05 at 17 29 32](https://cloud.githubusercontent.com/assets/1445635/6507806/5063c55c-c35d-11e4-91da-f33d0272e17a.png)

**Comment by tsdh** [comment]
Ah, cool.  So that seems to be a missing feature in Zeal.  Sorry for the noise then. :-)

Out of interest: How are methods/fields indexed in the SQLite database, i.e., when adding to the table the values for `name`, `type`, and `path` what do you provide as `name`?  (Sorry, my Objective-C skills are about zero.  I've looked at the code but it became not clear to me.)

**Comment by Kapeli** [comment]
This line does the add to the database: https://github.com/Kapeli/javadocset/blob/master/javadocset/DHIndexer.m#L122.

You could also just open the docSet.dsidx in a SQLite manager and see what is there :)

**Comment by tsdh** [comment]
Hm, ok, the anchor of the innerText.  I'm still not enlightened. ;-)

So let's check the DB.

```
]% sqlite3 ~/.local/share/Zeal/Zeal/docsets/Java_SE8.docset/Contents/Resources/docSet.dsidx
SQLite version 3.8.8.3 2015-02-25 13:29:11
Enter ".help" for usage hints.
sqlite> .tables
ZAPILANGUAGE              ZORDEREDSUBNODE           Z_2ADOPTEDBY            
ZCONTAINER                ZPARAMETER                Z_2SUBCLASSEDBY         
ZDISTRIBUTIONVERSION      ZRETURNVALUE              Z_3DEPRECATEDININVERSE  
ZDOCSET                   ZTOKEN                    Z_3INTRODUCEDININVERSE  
ZDOWNLOADABLEFILE         ZTOKENGROUP               Z_3REMOVEDAFTERINVERSE  
ZFILEPATH                 ZTOKENMETAINFORMATION     Z_8RELATEDDOCSINVERSE   
ZHEADER                   ZTOKENTYPE                Z_8RELATEDNODESINVERSE  
ZNODE                     Z_14RELATEDGROUPS         Z_8RELATEDSCINVERSE     
ZNODEURL                  Z_14RELATEDTOKENSINVERSE  Z_METADATA              
ZNODEUUID                 Z_1NODES                  Z_PRIMARYKEY            
sqlite> 
```

Argh.  It seems it uses a completely different DB schema than documented at http://kapeli.com/docsets which only creates a `searchIndex` table.

**Comment by Kapeli** [comment]
Ah, sorry. That's the Apple docset index format. Entries get added into the ZTOKEN table.

**Comment by tsdh** [comment]
Ok, thank you.
