### ISSUE TITLE
Creating javadoc docsets on non-Mac OS X platforms

### ISSUE THREAD

**Issue by Ramblurr** [Kapeli/javadocset#5]
The Zeal docs say to follow Dash's instructions for generating docsets.

I want to create a docset from custom javadocs, but the [dash instructions](https://github.com/Kapeli/javadocset#readme) require an OS X specific program.

Could we get some platform independent instructions for generating docsets from javadocs?

**Comment by Kapeli** [comment]
Nope, sorry. This tool is written in Objective-C and there's no way to run it on any other platform as far as I know.

**Comment by Ramblurr** [comment]
Oops @Kapeli  I thought this was the Zeal repo, my bad. Reporting this over there :)

**Comment by vspinu** [comment]
There is a go port https://github.com/william8th/javadocset. Worked for me on ubuntu. It creates a `docset.dsidx` instead of the common `docSet.dsidx` database though. But I guess dash front-ends should recognize both.

**Comment by Kapeli** [comment]
I've added https://github.com/william8th/javadocset to the README. Thanks for letting me know about it!
