### ISSUE TITLE
Errors compiling docset from Vaadin's javadoc v7.4.3

### ISSUE THREAD

**Issue by ewall** [Kapeli/javadocset#6]
Figured I should finally tell you that the javadocset program chokes on some of Vaadin's javadocs... I thought it was working okay--the content is all there--but now I realize that it isn't indexing the items which showed errors.

Here's the javadoc library I'm running it on: [https://vaadin.com/downloading?package=release/7.4/7.4.3/vaadin-all-7.4.3-javadoc.jar]()

...and here's the errors I see when running javadocset: [https://gist.github.com/ewall/53bbbd2ef99af9c80c2a]()

Note: I'm using the latest version of javadocset (freshly downloaded today), but past versions have had roughly the same results.

Thanks!

**Comment by Kapeli** [comment]
Thanks for letting me know! This should now be fixed.

**Comment by ewall** [comment]
Well, that was fast! And indeed, it did resolve the issue.

I'll have an updated docset ready in a few minutes.
