### ISSUE TITLE
UTF-8 Error in generating docset

### ISSUE THREAD

**Issue by soh-i** [Kapeli/javadocset#7]
`javadocset` showed following error messages.
```
reating docset structure...done
Copying files...done
Start indexing...
Indexing index-all.html...
Warning: could not determine type for a. Please tell the developer about this!

a - ã‚¯ãƒ©ã‚¹ ã®staticå¤‰æ•°htsjdk.samtools.util.SequenceUtil and

Warning: could not determine type for A. Please tell the developer about this!

A - ã‚¯ãƒ©ã‚¹ ã®staticå¤‰æ•°htsjdk.samtools.util.SequenceUtil and
....
```
I think `javadocset` command cant handle UTF-8 string, these corrupted strings maybe caused by NSString or something. my Mac OS locale is set to `LANG="ja_JP.UTF-8"`.

I'm heavy Dash.app user I am looking forward to next release fixed this issue!

Thanks.

**Comment by Kapeli** [comment]
Where can I download the docs so I can replicate this issue?
