### ISSUE TITLE
The API folder does not contain any index files

### ISSUE THREAD

**Issue by adrianbrink** [Kapeli/javadocset#8]
Hi,

I downloaded [http://algs4.cs.princeton.edu/code/javadoc/](url) this docset with httrack to my computer and I am trying to run ./javadocset on it. However when I do so, it tells me this: 

> Error: The API folder you specified does not contain any index files (either a index-all.html file or a index-files folder) and is not valid. Please contact the developer if you receive this error by mistake.

Any advice?

**Comment by Kapeli** [comment]
Maybe they deleted the index files? Neither http://algs4.cs.princeton.edu/code/javadoc/index-files/index-1.html or http://algs4.cs.princeton.edu/code/javadoc/index-all.html seem to exist.

**Comment by adrianbrink** [comment]
and they are definitely needed i guess?

**Comment by Kapeli** [comment]
For this docset indexer, yes. You might be able to write your own docset indexer that doesn't use them though.
