### ISSUE TITLE
How to process Groovy scripts/singleton classes?

### ISSUE THREAD

**Issue by nre-ableton** [Kapeli/javadocset#9]
So I've been using `javadocset` to generate docsets for [Jenkins Pipeline Libraries](https://jenkins.io/doc/book/pipeline/shared-libraries/), which are written in Groovy and use `groovydoc` for documentation. `javadocset` does not process the global singletons, and I get the following error message:

```
Warning: could not determine type for exampleClass. Please tell the developer about this!

exampleClass - Script in exampleClass and
```

Here's a bit of background information on the topic. The general directory structure of a Jenkins Pipeline Library is as such:

```
.
├── src
│   └── com
│       └── packagename
│           └── ExampleClass.groovy
├── test
│   ├── com
│   │   └── packagename
│   |       └── ExampleClassTest.groovy
│   └── resources
└── vars
    └── exampleClass.groovy
```

Classes exist in `src` and global singleton variables, usually thin wrappers around the class, are in `vars`. Most global singletons look like this:

```groovy
// exampleClass.groovy
import com.packagename.ExampleClass as ExampleClass

ExampleClass create(Map args) {
  return new ExampleClass(args)
}

def doStuff(Map args) {
  return new ExampleClass(args).doStuff()
}
```

The reason for providing a singleton is to spare the project's `Jenkinsfile` some boilerplate code for the `import` and `new` statements. Jenkins internally creates a class for these files, even though they lack a `class` declaration and appear as a regular Groovy script.

`javadocset` generates documentation correctly for classes, but not these singletons. Having them in our docsets is very important to our users, since most developers interface with them in their `Jenkinsfile`s rather than the classes.

I'm not sure if this is exactly a "bug" in `javadocset` or not, but regardless, I would really like to find a way to include documentation for such objects in our docsets.

**Comment by Kapeli** [comment]
Can you give me a link where I can download the docs you're trying to generate the docset from?

Please note that "javadocset" doesn't care about the source code at all. It just looks at the HTML docs, specifically the index-*.html files.

**Comment by nre-ableton** [comment]
@Kapeli Sure, here's the generated groovydocs for the [python-pipeline-utils library](https://github.com/AbletonDevTools/python-pipeline-utils): https://drive.google.com/file/d/18ybdOkgoKjKqQNu-gTKW51YEE1UqAQ06/view?usp=sharing

This was generated by running:

```
$ pandoc -f markdown -t html -o out/overview.html README.md
$ groovydoc -sourcepath $PWD:/$PWD/src -d ./out/docs \
    -overview ./out/overview.html -public -nomainforscripts com.ableton vars
```

Here's the generated docset, just to spare you a few clicks: https://drive.google.com/file/d/1aNMvX815d0BcB33ZqI65y1-tcsLMcYnO/view?usp=sharing

**Comment by Kapeli** [comment]
I've got the Scripts to show up in the docset. Try to redownload https://kapeli.com/javadocset.zip and regenerate the docset. Does this fix the issue?

If something is still missing from the docset index, please let me know where inside the HTML docs that something is documented so I can look into it.

**Comment by nre-ableton** [comment]
@Kapeli it's looking much better! 👍 So now I see all the singletons in a `scripts` dropdown, which is great. The application also does not print any errors on the console when I run it. However, the list of classes seems to be missing some entries. Here's a screenshot for the same aforementioned library:

<img width="256" alt="Screen Shot 2019-03-15 at 12 45 37" src="https://user-images.githubusercontent.com/16208985/54434673-100f8b80-472f-11e9-9bab-cb3b9f438c56.png">

Here's the corresponding list of classes/singletons from the library:

```
$ tree -P "*.groovy" src/ vars/
src/
└── com
    └── ableton
        ├── Pipenv.groovy
        ├── PythonBuilder.groovy
        ├── PythonPackage.groovy
        ├── VirtualEnv.groovy
        └── VirtualEnvList.groovy
vars/
├── pipenv.groovy
├── pythonBuilder.groovy
├── pythonPackage.groovy
├── virtualenv.groovy
└── virtualenvs.groovy
```

**Comment by Kapeli** [comment]
`javadocset` looks in this file to generate the index: `docs/index-all.html`. Within that file, `virtualenvs` for example is documented as: `Script in virtualenvs`, while `VirtualEnvList` is documented as: `Class in com.ableton`.

Should "Script" just be turned into "Class" instead? See https://github.com/Kapeli/javadocset/blob/master/javadocset/DHIndexer.m#L107-L110.

**Comment by Kapeli** [comment]
I'm suggesting treating all Scripts as Classes, not the other way around.

**Comment by nre-ableton** [comment]
@Kapeli Ah, I see, I think I misunderstood your previous post. Anyways, I guess that could work. I kind of like having them ordered separately under "Scripts", but if it's easier to just show everything under "Classes" that would be fine as well.

**Comment by Kapeli** [comment]
Having them separate in “Scripts” is what you have now. So is it ok to
leave things as is and close this issue?

**Comment by nre-ableton** [comment]
@Kapeli Yes, we could close this issue, but then should I open another issue for the missing classes?

**Comment by Kapeli** [comment]
I don’t understand. Aren’t the missing classes the Scripts?

**Comment by nre-ableton** [comment]
@Kapeli Sorry, I think we had a miscommunication. What I meant to say in my previous message (https://github.com/Kapeli/javadocset/issues/9#issuecomment-473287072) was that the scripts are there, but some classes are not listed there. However, I don't think that the missing classes are due to a change which was made to `javadocset`.

So to be clear, I will close this issue and open up another one for the missing classes, since it is an unrelated issue. Sorry for the confusion and thanks again for the fix!
